/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-error': '#690005',
        'on-tertiary': '#003907',
        surface: '#0B0C10',
        'text-muted': '#A1ECFB',
        'secondary-fixed-dim': '#00dddd',
        'inverse-primary': '#6a5f00',
        'surface-tint': '#dec800',
        'outline-variant': '#4b4731',
        error: '#ffb4ab',
        'on-tertiary-container': '#007518',
        'surface-bright': '#38393e',
        'tertiary-fixed': '#72ff70',
        'surface-container-high': '#292a2e',
        'error-container': '#93000a',
        'primary-container': '#ffe600',
        'surface-container-low': '#1a1b20',
        'secondary-fixed': '#15fbfb',
        'surface-container': '#1f1f24',
        'on-secondary-fixed': '#002020',
        'tertiary-fixed-dim': '#00e639',
        'secondary-container': '#03f8f8',
        'success-neon': '#00FF41',
        'on-background': '#e3e2e8',
        'surface-container-highest': '#343439',
        outline: '#ffe600',
        'on-primary-container': '#000000',
        tertiary: '#ffffff',
        'on-secondary-fixed-variant': '#004f4f',
        'on-surface': '#e3e2e8',
        'tertiary-container': '#72ff70',
        'on-tertiary-fixed': '#002203',
        'on-primary-fixed-variant': '#504700',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#201c00',
        background: '#0B0C10',
        'on-secondary-container': '#006e6e',
        secondary: '#f1fffe',
        'warning-neon': '#FFE600',
        'surface-variant': '#1f1f24',
        'surface-dim': '#0B0C10',
        'surface-container-lowest': '#0d0e12',
        'on-surface-variant': '#cdc7aa',
        primary: '#ffe600',
        'primary-fixed-dim': '#dec800',
        'on-primary': '#000000',
        'inverse-surface': '#e3e2e8',
        'primary-fixed': '#ffe600',
        'on-secondary': '#003737',
        'text-primary': '#E0E0E0',
        'on-tertiary-fixed-variant': '#00530e',
        'surface-panel': '#1A1D20',
        'inverse-on-surface': '#2f3035',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        headline: ['"Chakra Petch"', '"Space Grotesk"', 'sans-serif'],
        'headline-lg': ['"Chakra Petch"', '"Space Grotesk"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
